### ISSUE TITLE
superagent as peerDep

### ISSUE THREAD

**Issue by slightlytyler** [maroshii/sdktor#3]
Looking into mocking strategies and https://github.com/A/superagent-mocker looks good. If we use something like this `sdktor` should have `superagent` as peerDep so it can be versioned independently

**Comment by maroshii** [comment]
Not sure about this one. I'm in favour of drop-in dependencies in general. I think superagent should be an implementation detail of sdktor.
I'm 100% in favour of adding mocking capabilities though but I rather do this as first class capability in sdktor rather than exposing the library internals. We can always use [nock](https://github.com/node-nock/nock) to intercept requests in a nodejs enviroment from the callers side without making changes to sdktor.

----

Following the sdktor interface I was thinking of adding a `mock()` method alongside `at()` which would mock response from there on:


```js
import sdktor from 'sdktor';

const mock = sdktor('/api').mock({
  // just an example, not sure about this
  get: {
    '/container/json': myListMock,
    'container/:id/json': myItemMock,
  },
  post: {
    'container/:id/start': {},
  }
});
const sdk = mock.at('/containers');
const list = sdk.get('/json');
const inspect = sdk.get('/:id/json');
const start = sdk.post('/:id/start');


sdk.get('/json')({ all: true })
```

We would then hook it up into nock/superagent-mocker internally (somehow).

**Comment by maroshii** [comment]
cc @rogeliog
